name: Bump version, create new tag and release point
on:
  push:
    branches:
      - main

jobs:
  bump_version:
    name: Bump version, create tag/release point
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
