name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, windows, macos]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/peek-rs
            asset_name: peek-rs-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/peek-rs.exe
            asset_name: peek-rs-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/peek-rs
            asset_name: peek-rs-macos

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release --locked

      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.sset_name }}
          path: ${{ matrix.artifact_name }}a
